### ISSUE TITLE
Device ID readout fails after soft-reset

### ISSUE THREAD

**Issue by emha69** [STMicroelectronics/stm32-lsm6dso#1] opened 2024-05-14 11:57 UTC
When the hosting CPU is soft reset (e.g. thru **HAL_NVIC_SystemReset()**) the **LSM6DSO_0_Probe()** function in **lsm6dso.c** will fail in the standard 4-wire SPI configuration, since the **LSM6DSO_ReadID()** in most cases returns 0 (zero) for the device ID.

Working code fix, that has been successfully tested:

In the function **int32_t LSM6DSO_RegisterBusIO()** the following code should be added, after checking, if the bus is in the 3-wire SPI configuration.
```
      if (pObj->IO.BusType == LSM6DSO_SPI_3WIRES_BUS)
      {

        if (pObj->is_initialized == 0U)
        {
          uint8_t data = 0x0C;

          if (LSM6DSO_Write_Reg(pObj, LSM6DSO_CTRL3_C, data) != LSM6DSO_OK)
          {
            ret = LSM6DSO_ERROR;
          }
        }
      }
      else { 
         // FIX for failing device ID readout after soft-reset

    	  if (LSM6DSO_DISABLE_I3C(pObj) != LSM6DSO_OK) {
    		  ret = LSM6DSO_ERROR;
    	  }

    	  if (LSM6DSO_RESET_CHIP(pObj) != LSM6DSO_OK) {
    		  ret = LSM6DSO_ERROR;
    	  }
      }
```

The functions DISABLE_I3C and CHIP RESET used above have been added to the  lsm6dso.c

```
int32_t LSM6DSO_DISABLE_I3C(LSM6DSO_Object_t *pObj)
{
	if (lsm6dso_i3c_disable_set(&(pObj->Ctx), 0x80) != LSM6DSO_OK) {
		return LSM6DSO_ERROR;
	}

	return LSM6DSO_OK;
}

int32_t LSM6DSO_RESET_CHIP(LSM6DSO_Object_t *pObj)
{
	if (lsm6dso_reset_set(&(pObj->Ctx), 0x01) != LSM6DSO_OK) {
		return LSM6DSO_ERROR;
	}

	return LSM6DSO_OK;
}
```
Maybe the same is the case in 3-wire configuration, but I was not able to test it.

**Comment by KRASTM** [comment] 2024-05-17 10:25
Hello @emha69,

Thank you for the report.
Can you please share more details, such as:
- Do you use an STM board or a custom board (which µC)?
- Your project config and/or an extract of code so we can reproduce it.

With regards.

**Comment by emha69** [comment] 2024-05-17 11:41
No, I am using custom board in two different MCU type variants : STM32L562 and STM32L4P5. Both MCUs run (more or less) the same code, and the reset effect is (mostly) same.

Besides that, it is the original STM code, except few functions added (e.g. abstractions for register functions as shown in my example).

MCU config files attached.

[VIBS_L5C.zip](https://github.com/STMicroelectronics/stm32-lsm6dso/files/15348534/VIBS_L5C.zip)
[STM-L4B-V2.zip](https://github.com/STMicroelectronics/stm32-lsm6dso/files/15348535/STM-L4B-V2.zip)

**Comment by KRASTM** [comment] 2024-05-17 15:37
Hello,

In fact, there is an example BSP [`MotionSensor_demo`](https://github.com/STMicroelectronics/STM32CubeL5/tree/master/Projects/STM32L562E-DK/Examples/BSP) with STML562E-DK board. I have tested and work fine even with the soft reset, I didn't get an error with the function **LSM6DSO_Probe()** or **LSM6DSO_ReadID()**.
For information, the example based on I2C not SPI.

I will try to analyze and test with your config.

With regards.

**Comment by emha69** [comment] 2024-05-18 07:44
Reading similar reports around the internet, the problem with reading out the ID initially seems to be related to the SPI.
Using the chip in high-performance streaming mode requires use of SPI. So, I am looking forward, to see what you find out with SPI.

**Comment by KRASTM** [comment] 2024-05-21 10:08
Hello @emha69,

Unfortunately, the component LSM6DSO on the STM32L562-DK board is driven by I²C, even the connections. 
Sorry from my side, I cannot test your project or reproduce the issue with SPI.

I found some links related to this topic in our community, maybe it can help you to solve your problem:
[Link1](https://community.st.com/t5/mems-sensors/lsm6dso-issues-with-spi/td-p/176828)
[Link2](https://community.st.com/t5/mems-sensors/lsm6dso-spi-communication-problem/td-p/391931)

Otherwise, your issue it's related to the product rather than Embedded software. So, you can submit a post to the ST [Community](https://community.st.com/t5/mems-and-sensors/ct-p/mems-sensors).

Since this issue is not directly related to the STM32Cube firmware but rather to our ecosystem, please allow me then to close this thread. Thank you for your comprehension.

With regards.

**Comment by emha69** [comment] 2024-05-21 11:34
Hello @KRASTM,

I understand, that you are not willing to change the code, although I think there are ST boards out there that are using SPI with LSM6DSO, since this problem is IMHO not directly related to the STML5 series. However, it is also fine with me, if we have this issue and workaround noted here, if somebody encounters the same problem.

**Comment by KRASTM** [comment] 2024-05-28 13:23
Hello @emha69,

As I said before, I didn't manage to reproduce the issue with the means on board, but you can submit a post to the ST [Community](https://community.st.com/t5/mems-and-sensors/ct-p/mems-sensors).

Please, allow me to close this issue.

With regards.

**Closed as not planned by KRASTM** 2024-05-28 13:23 UTC
Labels: enhancement, wontfix, bsp, spi
